"""Add start_time and end_time to appointments

Revision ID: 61b015b66f92
Revises: 9fb35c22f4c4
Create Date: 2024-12-04 15:15:12.115301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b015b66f92'
down_revision: Union[str, None] = '9fb35c22f4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.alter_column('availabilities', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('availabilities', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availabilities', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('availabilities', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
